name: "Run TODO to Issue"
on: push
jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: "actions/checkout@v3"
            - name: "TODO to Issue"
              uses: "alstr/todo-to-issue-action@v4"